apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: blackboxgameengine
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blackboxgameengine
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 90Mi